apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  namespace: dev
  labels:
    app: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1-container
          image: REPOSITORY_TAG
          ports:
            - containerPort: 80
          env:
            - name: MONGODBCONFIG_CONNECTIONSTRING
              value: "mongodb://mongo-service.svc.cluster.local:27017"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: dev
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

