name: CICD
on: 
  pull_request:
    branches: 
      - "main"      
      #- "develop"     
    types: [closed]   
  workflow_dispatch:  
    
jobs:
  CI:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.5

  CD-Dev:
    # Condição para rodar somente se o PR for para a branch develop
    if: github.ref == 'refs/heads/develop'
    needs: [CI]
    uses: wallafi01/dotnet-eks/.github/workflows/deploy.yml@develop 
    with:
      environment: dev
      deploy_path: "ops/dev/deploy.yml"
    secrets: inherit


  CD-Prod:
    # Condição para rodar somente se o PR for para a branch main
    if: github.ref == 'refs/heads/main'
    needs: [CI]
    uses: wallafi01/dotnet-eks/.github/workflows/deploy.yml@main    
    with:
      environment: prod
      deploy_path: "ops/prod/deploy.yml"      
    secrets: inherit